function [B,B1] = controlMatrixSolutionRocketLandingFull(t,X,U,BodyMap)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

Nodes   = length(t);
dt      = diff(t);

%% Retrieve Environment

% Thrust Model
cex       = BodyMap.ThrustModel.ceffVac;

%%
B  = zeros(size(X,1),size(U,1),Nodes-1);
B1 = zeros(size(X,1),size(U,1),Nodes-1);
switch BodyMap.ThrustModel.collocationMethod
    case {'zoh','floor'}
        switch BodyMap.DynamicModel.controlVariable
            case 'thrust'
                M        = X(7,:);
                for ii = 1:Nodes-1
                    B(:,:,ii) = [...
                        dt(ii)^2/2*eye(3)/M(ii),zeros(3,1);...
                        dt(ii)*eye(3)/M(ii),zeros(3,1);...
                        zeros(1,3),-dt(ii)/cex;...
                        ];
                end
            case 'acceleration'
                for ii = 1:Nodes-1
                    B(:,:,ii) = [...
                        dt(ii)^2/2*eye(3),zeros(3,1);...
                        dt(ii)*eye(3),zeros(3,1);...
                        zeros(1,3),-dt(ii)/cex;...
                        ];
                end
        end
    case {'foh','linear'}
        switch BodyMap.DynamicModel.controlVariable
            case 'thrust'
                M        = X(7,:);
                for ii = 1:Nodes-1
                    B(:,:,ii) = [...
                        dt(ii)^2/3*eye(3)/M(ii),zeros(3,1);...
                        dt(ii)/2*eye(3)/M(ii),zeros(3,1);...
                        zeros(1,3),-dt(ii)/2/cex;...
                        ];
                    B1(:,:,ii) = [...
                        dt(ii)^2/6*eye(3)/M(ii+1),zeros(3,1);...
                        dt(ii)/2*eye(3)/M(ii+1),zeros(3,1);...
                        zeros(1,3),-dt(ii)/2/cex;...
                        ];
                end
            case 'acceleration'
                for ii = 1:Nodes-1
                    B(:,:,ii) = [...
                        dt(ii)^2/3*eye(3),zeros(3,1);...
                        dt(ii)/2*eye(3),zeros(3,1);...
                        zeros(1,3),-dt(ii)/2/cex;...
                        ];
                    B1(:,:,ii) = [...
                        dt(ii)^2/6*eye(3),zeros(3,1);...
                        dt(ii)/2*eye(3),zeros(3,1);...
                        zeros(1,3),-dt(ii)/2/cex;...
                        ];
                end
        end
end
end

